### ISSUE TITLE
vicen_m units and description

### ISSUE THREAD

**Issue by aidanheerdegen** [COSIMA/metadata#2]
The variable `vicen_m` has weird units. It is an ice volume, but has units of `m`. This comment in the code gives the reasoning

https://github.com/COSIMA/cice5/blob/f54f557188cdcd931effe3cf34bd09cd12093532/source/ice_state.F90#L16-L18

but it isn't clear in the data file. 

There is currently no attribute file for `vicen_m`, as there is no variable specific changes that need to be made, as there is no `standard_name` for it.

We could make a `vicen_m.yaml` file with a comment field, and put in some more explanation

```yaml
variables:
    vicen_m:
        comment: "Some nice words to explain this variable"
```
